from .devstack import *

INSTALLED_APPS += ('appsembler_cms', 'appsembler_lms',)

APPSEMBLER_SECRET_KEY = "secret_key"
OAUTH_ENFORCE_SECURE = False

APPSEMBLER_FEATURES = ENV_TOKENS.get('APPSEMBLER_FEATURES', {})
TESTDRIVE_TRIAL_DAYS = APPSEMBLER_FEATURES.get('TESTDRIVE_TRIAL_DAYS', 14)
ENFORCE_TESTDRIVE_EXPIRATION = APPSEMBLER_FEATURES.get('ENFORCE_TESTDRIVE_EXPIRATION', True)
