# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsembler_usage', '0003_grant_select_django_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagecalendarmonthly',
            name='sum_activated_admins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecalendarmonthly',
            name='sum_activated_instructors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecalendarmonthly',
            name='sum_active_admins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecalendarmonthly',
            name='sum_active_instructors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecalendarmonthly',
            name='sum_registered_admins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecalendarmonthly',
            name='sum_registered_instructors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomermonthly',
            name='sum_activated_admins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomermonthly',
            name='sum_activated_instructors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomermonthly',
            name='sum_active_admins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomermonthly',
            name='sum_active_instructors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomermonthly',
            name='sum_registered_admins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomermonthly',
            name='sum_registered_instructors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomerquarterly',
            name='sum_activated_admins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomerquarterly',
            name='sum_activated_instructors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomerquarterly',
            name='sum_active_admins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomerquarterly',
            name='sum_active_instructors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomerquarterly',
            name='sum_registered_admins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomerquarterly',
            name='sum_registered_instructors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomeryearly',
            name='sum_activated_admins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomeryearly',
            name='sum_activated_instructors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomeryearly',
            name='sum_active_admins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomeryearly',
            name='sum_active_instructors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomeryearly',
            name='sum_registered_admins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagecustomeryearly',
            name='sum_registered_instructors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagedaily',
            name='sum_activated_admins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagedaily',
            name='sum_activated_instructors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagedaily',
            name='sum_active_admins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagedaily',
            name='sum_active_instructors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagedaily',
            name='sum_registered_admins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagedaily',
            name='sum_registered_instructors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
